### ISSUE TITLE
base_url pointing to invalid path

### ISSUE THREAD

**Issue by Terry-BrooksJr** [blacknacoustic/whatdivisionisitbot#1]
Saw your request for Code Review on Python Discord Server. This may not be the reason your bots not is working, There are a lot of ENV and Secrets so it naturally wouldn't work in my codespace but it could be a contributing reason. 

`base_url = f'https://api.github.com/repos/{repo_owner}/{repo_name}/contents/{file_path}'`

After the formatted string interpolation, the base URL resolves to `https://api.github.com/repos/blacknacoustic/contents/currentdivision.txt`

Your current file structure is
`
.
├── currentdivision.txt
├── Pipfile
├── Procfile
├── README.md
├── requirements.txt
├── runtime.txt
├── venv
│   ├── Lib
│   │   └── site-packages
│   ├── pyvenv.cfg
`

Missing the `content` directory

**Comment by blacknacoustic** [comment]
So it should be just 

```base_url = f'https://api.github.com/repos/{repo_owner}/{repo_name}/{file_path}'```

or is it not supposed to be contents only content?
